version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - lavalink
    command: yarn prod
  lavalink:
    build:
      context: ./Lavalink
      dockerfile: Dockerfile
